### ISSUE TITLE
fix 'Critical dependency: the request of a dependency is an expression'

### ISSUE THREAD

**Issue by ctxhou** [Canner/coren#7]
when require `var`, webpack will throw `Critical dependency: the request of a dependency is an expression` warning and it will break hmr.

**app.js**: https://github.com/Canner/coren/blob/master/server/app.js#L45-L47

solution reference:
* https://github.com/AngularClass/angular-starter/issues/993
* https://github.com/webpack/webpack-dev-server/issues/212

**Comment by ctxhou** [comment]
fix at https://github.com/Canner/coren/commit/e92978f471ec0ddfa48902818bfe4dad9d7bf81d

Because user will not use `App` this component, remove it from coren api.

**Comment by ssougnez** [comment]
Hi,

I just updated angular to v5.0.0-beta.6 and this error is back (I didn't have it with version 5.0.0-beta.5. Here is the error:

> WARNING in C:/.../node_modules/@angular/core/esm5/index.js
> 5697:15-36 Critical dependency: the request of a dependency is an expression
> WARNING in C:/.../node_modules/@angular/core/esm5/index.js
> 5713:15-102 Critical dependency: the request of a dependency is an expression

Here is the supposed fix in the webpack.config.json. It used to work for a few weeks now (since the project creation) and started to fail just after the upgrade.

`new webpack.ContextReplacementPlugin(/angular(\\|\/)core(\\|\/)@angular/, helpers.root("src"))`

Regards

**Comment by ctxhou** [comment]
Hi @ssougnez,
I think your error is caused by angular. You can open this issue on their repo.

**Comment by ssougnez** [comment]
Oops, sorry, I came from a link in the angular repo, I didn't notice I ended up on another one.
